-- =========================================================================
-- ⚡ SUPABASE POSTGRESQL SCHEMA (ZAMBOANGA CITY BRANCHES)
-- =========================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Branches Table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    address TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    settings JSONB DEFAULT '{"tax_rate": 0.12, "currency": "PHP"}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Products & Global Pricing Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    barcode TEXT,
    base_price NUMERIC(10, 2) NOT NULL,
    cost_price NUMERIC(10, 2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Branch Inventory Matrix Table
CREATE TABLE IF NOT EXISTS branch_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    stock_quantity NUMERIC(12, 2) DEFAULT 0.00,
    alert_threshold NUMERIC(12, 2) DEFAULT 10.00,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(branch_id, product_id)
);

-- 4. Daily Batch Sync Ingestion Table
CREATE TABLE IF NOT EXISTS daily_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    batch_id TEXT UNIQUE NOT NULL,
    device_serial TEXT,
    sync_date DATE NOT NULL,
    orders_count INT NOT NULL,
    gross_sales NUMERIC(12, 2) NOT NULL,
    cash_sales NUMERIC(12, 2) DEFAULT 0.00,
    ewallet_sales NUMERIC(12, 2) DEFAULT 0.00,
    card_sales NUMERIC(12, 2) DEFAULT 0.00,
    orders_payload JSONB NOT NULL,
    timeclocks_payload JSONB DEFAULT '[]',
    shift_summary JSONB,
    received_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Staff Records
CREATE TABLE IF NOT EXISTS staff_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'cashier',
    pin_code TEXT,
    hourly_rate NUMERIC(10, 2) DEFAULT 85.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Row-Level Security (RLS) Configuration
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access on branches" ON branches FOR ALL USING (true);
CREATE POLICY "Allow public access on products" ON products FOR ALL USING (true);
CREATE POLICY "Allow public access on branch_inventory" ON branch_inventory FOR ALL USING (true);
CREATE POLICY "Allow public access on daily_batches" ON daily_batches FOR ALL USING (true);
CREATE POLICY "Allow public access on staff_records" ON staff_records FOR ALL USING (true);

-- =========================================================================
-- 🌱 INITIAL SEED DATA (ZAMBOANGA CITY BRANCHES)
-- =========================================================================

-- Upsert Zamboanga City Branches
INSERT INTO branches (id, name, code, address, phone) VALUES
(1, 'KCC Mall de Zamboanga', 'BR-ZAM-01', 'Gov. Camins Ave, Zamboanga City', '+63 917 621 0001'),
(2, 'Yubenco Star Mall Tetuan', 'BR-ZAM-02', 'Tetuan Highway, Zamboanga City', '+63 917 622 0002'),
(3, 'Paseo del Mar Waterfront Kiosk', 'BR-ZAM-03', 'Valderrosa St, Zone IV, Zamboanga City', '+63 917 623 0003')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    address = EXCLUDED.address,
    phone = EXCLUDED.phone;

-- Insert Products
INSERT INTO products (id, category, name, base_price, cost_price) VALUES
(1, 'Coffee & Drinks', 'Iced Caramel Macchiato', 145.00, 45.00),
(2, 'Coffee & Drinks', 'Spanish Latte (Cold)', 135.00, 40.00),
(3, 'Coffee & Drinks', 'Americano Espresso', 95.00, 20.00),
(4, 'Bakery & Pastries', 'Butter Croissant', 85.00, 30.00),
(5, 'Bakery & Pastries', 'Chocolate Lava Muffin', 95.00, 35.00),
(6, 'Bakery & Pastries', 'Cheese Ensaymada', 75.00, 25.00),
(7, 'Hot Meals', 'Beef Tapa Rice Bowl', 180.00, 70.00),
(8, 'Hot Meals', 'Chicken Teriyaki Bowl', 165.00, 60.00),
(9, 'Quick Snacks', 'Truffle Fries', 120.00, 40.00)
ON CONFLICT (id) DO NOTHING;

-- Insert Initial Branch Stocks
INSERT INTO branch_inventory (branch_id, product_id, stock_quantity, alert_threshold) VALUES
(1, 1, 80, 10), (2, 1, 50, 10), (3, 1, 30, 5),
(1, 2, 100, 10), (2, 2, 75, 10), (3, 2, 40, 5),
(1, 3, 120, 10), (2, 3, 90, 10), (3, 3, 60, 5),
(1, 4, 35, 10), (2, 4, 20, 10), (3, 4, 15, 5),
(1, 5, 25, 10), (2, 5, 18, 10), (3, 5, 10, 5),
(1, 6, 40, 10), (2, 6, 30, 10), (3, 6, 20, 5),
(1, 7, 50, 10), (2, 7, 35, 10), (3, 7, 0, 5),
(1, 8, 45, 10), (2, 8, 40, 10), (3, 8, 0, 5),
(1, 9, 60, 10), (2, 9, 40, 10), (3, 9, 25, 5)
ON CONFLICT (branch_id, product_id) DO NOTHING;

-- Insert Cashiers
INSERT INTO staff_records (id, branch_id, name, role, pin_code, hourly_rate) VALUES
(1, 1, 'Maria Santos (KCC)', 'cashier', '1234', 85.00),
(2, 2, 'John Dela Cruz (Tetuan)', 'cashier', '5678', 85.00),
(3, 3, 'Ana Reyes (Paseo)', 'cashier', '4321', 80.00)
ON CONFLICT (id) DO NOTHING;
