-- =========================================================================
-- ⚡ KUYAVINCE POS: CLEAN PRODUCTION SETUP & INITIAL CONFIGURATION
-- =========================================================================

-- 1. Drop existing demo tables cleanly
DROP TABLE IF EXISTS daily_batches CASCADE;
DROP TABLE IF EXISTS branch_inventory CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS staff_records CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

-- 2. Branches Table (with Branch Import Code for Sunmi Auto-Provisioning)
CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    import_code TEXT UNIQUE NOT NULL, -- e.g. 'KV-BR01', 'KV-BR02', 'KV-BR03'
    address TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    settings JSONB DEFAULT '{"tax_rate": 0.12, "currency": "PHP"}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Products & Global Pricing Table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL DEFAULT 'General',
    name TEXT NOT NULL,
    barcode TEXT,
    image_url TEXT,
    base_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    cost_price NUMERIC(10, 2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Branch Inventory Matrix Table
CREATE TABLE branch_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    stock_quantity NUMERIC(12, 2) DEFAULT 0.00,
    alert_threshold NUMERIC(12, 2) DEFAULT 10.00,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(branch_id, product_id)
);

-- 5. Daily Batch Sync Ingestion Table
CREATE TABLE daily_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    batch_id TEXT UNIQUE NOT NULL,
    device_serial TEXT,
    sync_date DATE NOT NULL,
    orders_count INT NOT NULL DEFAULT 0,
    gross_sales NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    cash_sales NUMERIC(12, 2) DEFAULT 0.00,
    ewallet_sales NUMERIC(12, 2) DEFAULT 0.00,
    card_sales NUMERIC(12, 2) DEFAULT 0.00,
    orders_payload JSONB NOT NULL DEFAULT '[]',
    timeclocks_payload JSONB DEFAULT '[]',
    shift_summary JSONB DEFAULT '{}',
    received_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Staff Records Table
CREATE TABLE staff_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'cashier',
    pin_code TEXT NOT NULL,
    hourly_rate NUMERIC(10, 2) DEFAULT 85.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Configure Open RLS for Client / Admin Operations
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access on branches" ON branches FOR ALL USING (true);
CREATE POLICY "Allow public access on products" ON products FOR ALL USING (true);
CREATE POLICY "Allow public access on branch_inventory" ON branch_inventory FOR ALL USING (true);
CREATE POLICY "Allow public access on daily_batches" ON daily_batches FOR ALL USING (true);
CREATE POLICY "Allow public access on staff_records" ON staff_records FOR ALL USING (true);

-- 8. Clean Default Branches with Import Codes for Sunmi Devices
INSERT INTO branches (id, name, code, import_code, address, phone) VALUES
(1, 'Branch 1 - Main Hub', 'BR-01', 'KV-BR01', 'Zamboanga City', '+63 917 000 0001'),
(2, 'Branch 2 - Mall Outlet', 'BR-02', 'KV-BR02', 'Zamboanga City', '+63 917 000 0002'),
(3, 'Branch 3 - Kiosk', 'BR-03', 'KV-BR03', 'Zamboanga City', '+63 917 000 0003')
ON CONFLICT (id) DO NOTHING;
