-- =========================================================================
-- ⚡ SUPABASE POSTGRESQL SCHEMA (MASTER PRODUCT CATALOG & MULTI-BRANCH)
-- =========================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Branches Table
CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    import_code TEXT UNIQUE NOT NULL,
    address TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    settings JSONB DEFAULT '{"tax_rate": 0.12, "currency": "PHP"}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Master Products & Global Pricing Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL DEFAULT 'General',
    name TEXT NOT NULL,
    barcode TEXT,
    image_url TEXT,
    base_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    cost_price NUMERIC(10, 2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Branch Inventory Matrix Table (Supports Custom Branch Price Overrides)
CREATE TABLE IF NOT EXISTS branch_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    stock_quantity NUMERIC(12, 2) DEFAULT 0.00,
    price_override NUMERIC(10, 2) DEFAULT NULL, -- NULL falls back to products.base_price
    alert_threshold NUMERIC(12, 2) DEFAULT 10.00,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(branch_id, product_id)
);

-- 4. Daily Batch Sync Ingestion Table
CREATE TABLE IF NOT EXISTS daily_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
    batch_id TEXT UNIQUE NOT NULL,
    device_serial TEXT,
    sync_date DATE NOT NULL,
    orders_count INT NOT NULL,
    gross_sales NUMERIC(12, 2) NOT NULL,
    cash_sales NUMERIC(12, 2) DEFAULT 0.00,
    ewallet_sales NUMERIC(12, 2) DEFAULT 0.00,
    card_sales NUMERIC(12, 2) DEFAULT 0.00,
    orders_payload JSONB NOT NULL,
    timeclocks_payload JSONB DEFAULT '[]',
    shift_summary JSONB,
    received_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Staff Records
CREATE TABLE IF NOT EXISTS staff_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'cashier',
    pin_code TEXT,
    pin_salt TEXT,
    pin_hash TEXT,
    hourly_rate NUMERIC(10, 2) DEFAULT 85.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure pin_salt and pin_hash exist if table was previously created
ALTER TABLE staff_records ADD COLUMN IF NOT EXISTS pin_salt TEXT;
ALTER TABLE staff_records ADD COLUMN IF NOT EXISTS pin_hash TEXT;

-- 6. Row-Level Security (RLS) Configuration
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE branch_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public access on branches" ON branches;
CREATE POLICY "Allow public access on branches" ON branches FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on products" ON products;
CREATE POLICY "Allow public access on products" ON products FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on branch_inventory" ON branch_inventory;
CREATE POLICY "Allow public access on branch_inventory" ON branch_inventory FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on daily_batches" ON daily_batches;
CREATE POLICY "Allow public access on daily_batches" ON daily_batches FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on staff_records" ON staff_records;
CREATE POLICY "Allow public access on staff_records" ON staff_records FOR ALL USING (true);

-- =========================================================================
-- 🌱 INITIAL SEED DATA
-- =========================================================================

-- Upsert Branches
INSERT INTO branches (id, name, code, import_code, address, phone) VALUES
(1, 'Main Branch - Gateway 1', 'BR-GW01', 'KV-GW01', 'Gateway 1', '+63 917 000 0001'),
(2, 'Gateway Branch', 'BR-GW02', 'KV-GW02', 'Gateway Branch', '+63 917 000 0002')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    import_code = EXCLUDED.import_code,
    address = EXCLUDED.address,
    phone = EXCLUDED.phone;

-- Insert Master Product Catalog (44 Items)
INSERT INTO products (id, category, name, base_price, cost_price) VALUES
-- Beef
(1, 'Beef', 'Bulalo', 200.00, 80.00),
(2, 'Beef', 'Balbacua Solo', 120.00, 50.00),
(3, 'Beef', 'Beef Arroz Caldo', 70.00, 25.00),
(4, 'Beef', 'Beef Mami', 70.00, 25.00),
(5, 'Beef', 'Paklay', 80.00, 30.00),

-- Chicken
(6, 'Chicken', 'Fried Chicken (A la carte)', 50.00, 20.00),
(7, 'Chicken', 'Chicken Adobo', 50.00, 20.00),
(8, 'Chicken', 'Chicken Halang', 50.00, 20.00),
(9, 'Chicken', 'Sabaw Manok', 50.00, 18.00),
(10, 'Chicken', 'Chicken Barbecue', 70.00, 28.00),
(11, 'Chicken', 'Chicken Sisig (A la carte)', 50.00, 20.00),
(12, 'Chicken', 'Chicken Mami', 70.00, 25.00),
(13, 'Chicken', 'Chicken Arroz Caldo', 70.00, 25.00),

-- Fish
(14, 'Fish', 'Fried Fish', 50.00, 20.00),
(15, 'Fish', 'Paksiw Bangus', 50.00, 20.00),
(16, 'Fish', 'Soup Fish', 50.00, 18.00),

-- Value Meals (Unli Rice w/ Drinks)
(17, 'Value Meals', 'Fried Chicken Value Meal', 60.00, 25.00),
(18, 'Value Meals', 'Chicken Sisig Value Meal', 60.00, 25.00),
(19, 'Value Meals', 'Beef Pares Value Meal', 55.00, 22.00),

-- Combo Meals (Unli Rice w/ Drinks)
(20, 'Combo Meals', 'Beef Bulalo Meal', 130.00, 55.00),
(21, 'Combo Meals', 'Beef Balbacua Meal', 160.00, 65.00),
(22, 'Combo Meals', 'Beef Bicol Express Meal', 160.00, 65.00),
(23, 'Combo Meals', 'Chicken Sisig Meal', 130.00, 50.00),
(24, 'Combo Meals', 'Chicken Barbecue Meal', 130.00, 50.00),
(25, 'Combo Meals', 'Fried Chicken Meal', 120.00, 45.00),
(26, 'Combo Meals', 'Beef Pares Meal', 160.00, 60.00),

-- Sausages
(27, 'Sausages', 'Longganisa', 25.00, 10.00),
(28, 'Sausages', 'Hotdog', 15.00, 6.00),
(29, 'Sausages', 'Hungarian Sausage', 35.00, 15.00),

-- Noodles
(30, 'Noodles', 'Pancit Guisado', 30.00, 12.00),
(31, 'Noodles', 'Sotanghon Guisado', 30.00, 12.00),
(32, 'Noodles', 'Bihon', 30.00, 12.00),
(33, 'Noodles', 'Bam-e', 30.00, 12.00),

-- Drinks
(34, 'Drinks', 'Royal', 30.00, 15.00),
(35, 'Drinks', 'Coke', 30.00, 15.00),
(36, 'Drinks', 'Sprite', 30.00, 15.00),
(37, 'Drinks', 'Mountain Dew', 30.00, 15.00),
(38, 'Drinks', 'Calamansi Juice', 30.00, 10.00),
(39, 'Drinks', 'Bottled Water 1L', 35.00, 15.00),
(40, 'Drinks', 'Bottled Water 500ml', 25.00, 10.00),

-- Add-ons
(41, 'Add-ons', 'Boiled Egg', 20.00, 8.00),
(42, 'Add-ons', 'Sunny Side Up', 20.00, 8.00),
(43, 'Add-ons', 'Extra Rice', 15.00, 5.00),
(44, 'Add-ons', 'Extra Soup', 5.00, 1.00)
ON CONFLICT (id) DO UPDATE SET
    category = EXCLUDED.category,
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    cost_price = EXCLUDED.cost_price;

-- Insert Branch Stock & Price Overrides
-- Branch 1 (Main Branch - Gateway 1)
INSERT INTO branch_inventory (branch_id, product_id, stock_quantity, price_override, alert_threshold)
SELECT 1, id, 50.00, NULL, 10.00 FROM products
ON CONFLICT (branch_id, product_id) DO UPDATE SET
    stock_quantity = EXCLUDED.stock_quantity,
    price_override = EXCLUDED.price_override;

-- Branch 2 (Gateway Branch)
INSERT INTO branch_inventory (branch_id, product_id, stock_quantity, price_override, alert_threshold) VALUES
(2, 24, 40.00, 120.00, 10.00), -- Chicken BBQ Meal (₱120 vs default ₱130)
(2, 25, 40.00, 89.00, 10.00),  -- Fried Chicken Meal (₱89 vs default ₱120)
(2, 26, 35.00, 75.00, 10.00),  -- Beef Pares Meal (₱75 vs default ₱160)
(2, 12, 30.00, 65.00, 10.00),  -- Chicken Mami (₱65 vs default ₱70)
(2, 4,  30.00, 65.00, 10.00),  -- Beef Mami (₱65 vs default ₱70)
(2, 34, 50.00, NULL, 10.00),   -- Royal (₱30)
(2, 35, 50.00, NULL, 10.00),   -- Coke (₱30)
(2, 36, 50.00, NULL, 10.00),   -- Sprite (₱30)
(2, 37, 50.00, NULL, 10.00),   -- Mountain Dew (₱30)
(2, 38, 50.00, NULL, 10.00),   -- Calamansi Juice (₱30)
(2, 39, 40.00, NULL, 10.00),   -- Bottled Water 1L (₱35)
(2, 40, 60.00, NULL, 10.00)    -- Bottled Water 500ml (₱25)
ON CONFLICT (branch_id, product_id) DO UPDATE SET
    stock_quantity = EXCLUDED.stock_quantity,
    price_override = EXCLUDED.price_override;

-- Insert Cashiers
INSERT INTO staff_records (id, branch_id, name, role, pin_code, hourly_rate) VALUES
(1, 1, 'Maria Santos (Main Gateway 1)', 'cashier', '1234', 85.00),
(2, 2, 'John Dela Cruz (Gateway Branch)', 'cashier', '5678', 85.00)
ON CONFLICT (id) DO NOTHING;

